name: android-qt5_15_2
on: 
  # push代码时触发workflow
  push:
    paths:
      - '3rdparty/**'
      - 'examples/**'
      - 'mkspecs/**'
      - 'src/**'
      - '.qmake.conf'
      - 'TaoQuick.pro'
      - '.github/workflows/android-qt5_15_2.yml'
  # pull_request时触发workflow
  pull_request:
    paths:
      - '3rdparty/**'
      - 'examples/**'
      - 'mkspecs/**'
      - 'src/**'
      - '.qmake.conf'
      - 'TaoQuick.pro'
      - '.github/workflows/android-qt5_15_2.yml'               
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        qt_ver: [5.15.2]
        qt_target: [android]

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: android
          # Architecture for Windows/Android
          # arch: ${{ matrix.qt_arch }}          
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build android
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          qmake
          make